import type { PaperDraft } from "@deepscholar/contracts";

function latexHeader(draft: PaperDraft): string {
  const venueNote =
    draft.venue === "arxiv"
      ? "arXiv"
      : `${draft.venue} (当前使用通用 article 模板，尚未套对应会议 sty)`;
  return [
    "% Auto-generated by DeepScholar-Claw writing service",
    `% draftId: ${draft.draftId}`,
    `% venue: ${venueNote}`,
    "\\documentclass[11pt]{article}",
    "\\usepackage[utf8]{inputenc}",
    "\\usepackage{graphicx}",
    "\\usepackage{hyperref}",
    "\\usepackage{booktabs}",
    "\\title{" + draft.title + "}",
    "\\author{DeepScholar-Claw}",
    "\\date{}",
    "",
    "\\begin{document}",
    "\\maketitle",
    "",
  ].join("\n");
}

function latexSection(title: string, content: string): string {
  return ["\\section{" + title + "}", content.trim(), ""].join("\n");
}

function latexFigures(draft: PaperDraft): string {
  if (draft.figures.length === 0) {
    return "";
  }
  const rendered = draft.figures.map((figure) =>
    [
      "\\begin{figure}[t]",
      "\\centering",
      "\\includegraphics[width=0.8\\linewidth]{" + figure.path + "}",
      "\\caption{" + figure.caption + "}",
      "\\label{" + figure.latexRef + "}",
      "\\end{figure}",
      "",
    ].join("\n"),
  );
  return rendered.join("\n");
}

function latexCitations(draft: PaperDraft): string {
  if (draft.citations.length === 0) {
    return "";
  }
  const keys = draft.citations.join(",");
  return ["\\paragraph{Key References}", `This draft cites: \\cite{${keys}}.`, ""].join("\n");
}

export function renderPaperMainTex(draft: PaperDraft): string {
  return [
    latexHeader(draft),
    "\\begin{abstract}",
    draft.sections.abstract.trim(),
    "\\end{abstract}",
    "",
    latexSection("Introduction", draft.sections.introduction),
    latexSection(
      "Related Work",
      [draft.sections.relatedWork.trim(), latexCitations(draft)].join("\n").trim(),
    ),
    latexSection("Methodology", draft.sections.methodology),
    latexSection("Experiments", draft.sections.experiments),
    latexSection("Results", [draft.sections.results.trim(), latexFigures(draft)].join("\n").trim()),
    latexSection("Discussion", draft.sections.discussion),
    latexSection("Conclusion", draft.sections.conclusion),
    "\\bibliographystyle{plain}",
    "\\bibliography{refs}",
    "\\end{document}",
    "",
  ].join("\n");
}
