import { pathToFileURL } from "node:url";
import {
  approveBudgetRequest,
  rejectBudgetRequest,
  type ApprovalStatus,
  type BudgetApprovalRequest,
  validateBudgetApprovalRequest,
} from "./approvals.ts";
import {
  createAuditEntry,
  type AuditActor,
  type AuditDetails,
  type AuditEntry,
  validateAuditEntry,
} from "./audit.ts";
import {
  createBudgetEnvelope,
  createProjectCharter,
  type BudgetEnvelope,
  type CreateProjectCharterInput,
  type ProjectCharter,
  validateProjectCharter,
} from "./charter.ts";
import {
  collectUnverifiedClaims,
  createAssertion,
  createClaim,
  createEvidenceBinding,
  isAssertionVerified,
  isClaimVerified,
  type Assertion,
  type AssertionType,
  type BaselineComparison,
  type Claim,
  type ClaimAggregation,
  type ClaimAuditStatus,
  type ClaimStrength,
  type CreateAssertionInput,
  type CreateClaimInput,
  type CreateEvidenceBindingInput,
  type EvidenceBinding,
  validateAssertion,
  validateClaim,
  validateEvidenceBinding,
} from "./claims.ts";
import {
  createExperimentSpec,
  type CreateExperimentSpecInput,
  type ExperimentSpec,
  validateExperimentSpec,
} from "./experiment.ts";
import {
  createMemoryItem,
  type CreateMemoryItemInput,
  type MemoryItem,
  type MemoryLayer,
  validateMemoryItem,
} from "./memory.ts";
import { RESEARCH_PHASES, isResearchPhase, type ResearchPhase } from "./phases.ts";
import {
  createResearchPlanDraft,
  freezeResearchPlan,
  type BaselineSpec,
  type CreateResearchPlanDraftInput,
  type FreezeResearchPlanInput,
  type ResearchPlan,
  type ResearchPlanDraft,
  validateResearchPlan,
  validateResearchPlanDraft,
} from "./plan.ts";
import {
  createResearchProject,
  type IdeaProposal,
  type ProjectGateState,
  type ProjectLifecycleStatus,
  type ResearchProject,
  validateIdeaProposal,
  validateResearchProject,
} from "./project.ts";
import {
  createExperimentRun,
  type CreateExperimentRunInput,
  type ExperimentArtifact,
  type ExperimentExecutionRef,
  type ExperimentFailure,
  type ExperimentFailureType,
  type ExperimentRun,
  type ExperimentRunStatus,
  validateExperimentRun,
} from "./runs.ts";
import { CORE_SERVICE_IDS, type CoreServiceId, type ServiceDescriptor } from "./services.ts";
import { getNextResearchStep, isResearchStep, RESEARCH_STEPS, type ResearchStep } from "./steps.ts";
import { isIsoTimestamp, nowIsoTimestamp, type IsoTimestamp } from "./time.ts";
import type { ValidationIssue } from "./validation.ts";
import { isOneOf } from "./validation.ts";

export {
  CORE_SERVICE_IDS,
  RESEARCH_PHASES,
  RESEARCH_STEPS,
  approveBudgetRequest,
  collectUnverifiedClaims,
  createBudgetEnvelope,
  createAssertion,
  createAuditEntry,
  createClaim,
  createMemoryItem,
  createEvidenceBinding,
  createExperimentSpec,
  createExperimentRun,
  createProjectCharter,
  createResearchProject,
  createResearchPlanDraft,
  freezeResearchPlan,
  getNextResearchStep,
  isResearchPhase,
  isAssertionVerified,
  isClaimVerified,
  isIsoTimestamp,
  isOneOf,
  isResearchStep,
  nowIsoTimestamp,
  rejectBudgetRequest,
  validateAssertion,
  validateAuditEntry,
  validateClaim,
  validateBudgetApprovalRequest,
  validateEvidenceBinding,
  validateExperimentSpec,
  validateExperimentRun,
  validateIdeaProposal,
  validateMemoryItem,
  validateProjectCharter,
  validateResearchProject,
  validateResearchPlan,
  validateResearchPlanDraft,
};

export type {
  ApprovalStatus,
  Assertion,
  AssertionType,
  AuditActor,
  AuditDetails,
  AuditEntry,
  BaselineComparison,
  BaselineSpec,
  BudgetApprovalRequest,
  BudgetEnvelope,
  Claim,
  ClaimAggregation,
  ClaimAuditStatus,
  ClaimStrength,
  CoreServiceId,
  CreateAssertionInput,
  CreateClaimInput,
  CreateEvidenceBindingInput,
  CreateExperimentSpecInput,
  CreateExperimentRunInput,
  CreateMemoryItemInput,
  CreateProjectCharterInput,
  CreateResearchPlanDraftInput,
  EvidenceBinding,
  ExperimentArtifact,
  ExperimentExecutionRef,
  ExperimentFailure,
  ExperimentFailureType,
  ExperimentSpec,
  ExperimentRun,
  ExperimentRunStatus,
  FreezeResearchPlanInput,
  IdeaProposal,
  ProjectGateState,
  IsoTimestamp,
  MemoryItem,
  MemoryLayer,
  ProjectLifecycleStatus,
  ProjectCharter,
  ResearchPhase,
  ResearchPlan,
  ResearchPlanDraft,
  ResearchProject,
  ResearchStep,
  ServiceDescriptor,
  ValidationIssue,
};

export const contractSummary = {
  phases: RESEARCH_PHASES,
  steps: RESEARCH_STEPS,
  services: CORE_SERVICE_IDS,
};

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  console.log(JSON.stringify(contractSummary, null, 2));
}
