import { pathToFileURL } from "node:url";
import {
  approveBudgetRequest,
  rejectBudgetRequest,
  type ApprovalStatus,
  type BudgetApprovalRequest,
  validateBudgetApprovalRequest,
} from "./approvals.ts";
import {
  createAuditEntry,
  type AuditActor,
  type AuditDetails,
  type AuditEntry,
  validateAuditEntry,
} from "./audit.ts";
import {
  createBudgetEnvelope,
  createProjectCharter,
  type BudgetEnvelope,
  type CreateProjectCharterInput,
  type ProjectCharter,
  validateProjectCharter,
} from "./charter.ts";
import {
  collectUnverifiedClaims,
  createAssertion,
  createClaim,
  createEvidenceBinding,
  isAssertionVerified,
  isClaimVerified,
  type Assertion,
  type AssertionType,
  type BaselineComparison,
  type Claim,
  type ClaimAggregation,
  type ClaimAuditStatus,
  type ClaimStrength,
  type CreateAssertionInput,
  type CreateClaimInput,
  type CreateEvidenceBindingInput,
  type EvidenceBinding,
  validateAssertion,
  validateClaim,
  validateEvidenceBinding,
} from "./claims.ts";
import {
  createExperimentSpec,
  type CreateExperimentSpecInput,
  type ExperimentSpec,
  validateExperimentSpec,
} from "./experiment.ts";
import {
  createMemoryItem,
  type CreateMemoryItemInput,
  type MemoryItem,
  type MemoryLayer,
  validateMemoryItem,
} from "./memory.ts";
import {
  createPaperDraft,
  isPaperDraftStatus,
  isPaperVenueTemplateId,
  validatePaperCompileResult,
  validatePaperDraft,
  PAPER_DRAFT_STATUSES,
  PAPER_VENUE_TEMPLATES,
  type CreatePaperDraftInput,
  type PaperCompileResult,
  type PaperDraft,
  type PaperDraftStatus,
  type PaperFigure,
  type PaperSections,
  type PaperVenueTemplateId,
} from "./paper.ts";
import { RESEARCH_PHASES, isResearchPhase, type ResearchPhase } from "./phases.ts";
import {
  createResearchPlanDraft,
  freezeResearchPlan,
  type BaselineSpec,
  type CreateResearchPlanDraftInput,
  type FreezeResearchPlanInput,
  type ResearchPlanApproval,
  type ResearchPlan,
  type ResearchPlanDraft,
  validateResearchPlan,
  validateResearchPlanDraft,
} from "./plan.ts";
import {
  createResearchProject,
  type IdeaProposal,
  type ProjectGateState,
  type ProjectLifecycleStatus,
  type ResearchProject,
  validateIdeaProposal,
  validateResearchProject,
} from "./project.ts";
import {
  DEFAULT_REVIEW_THRESHOLDS,
  REVIEW_DIMENSIONS,
  REVIEWER_PERSONAS,
  REVIEW_VERDICTS,
  createPeerReview,
  createReviewRubric,
  isReviewDimensionId,
  isReviewVerdict,
  isReviewerPersona,
  validatePeerReview,
  validateReviewDecision,
  validateReviewRound,
  validateReviewRubric,
  type CreatePeerReviewInput,
  type CreateReviewRubricInput,
  type PeerReview,
  type ReviewDecision,
  type ReviewDimensionAssessment,
  type ReviewDimensionId,
  type ReviewerPersona,
  type ReviewRound,
  type ReviewRubric,
  type ReviewThresholds,
  type ReviewVerdict,
} from "./review.ts";
import {
  createExperimentRun,
  DOCKER_SANDBOX_PROFILES,
  EXPERIMENT_RUN_STATUSES,
  isDockerSandboxProfile,
  isExperimentRunStatus,
  type CreateExperimentRunInput,
  type DockerSandboxProfile,
  type ExperimentArtifact,
  type ExperimentExecutionRef,
  type ExperimentExecutionRequest,
  type ExperimentFailure,
  type ExperimentFailureType,
  type ExperimentRun,
  type ExperimentRunStatus,
  validateExperimentRun,
} from "./runs.ts";
import { CORE_SERVICE_IDS, type CoreServiceId, type ServiceDescriptor } from "./services.ts";
import { getNextResearchStep, isResearchStep, RESEARCH_STEPS, type ResearchStep } from "./steps.ts";
import { isIsoTimestamp, nowIsoTimestamp, type IsoTimestamp } from "./time.ts";
import type { ValidationIssue } from "./validation.ts";
import { isOneOf } from "./validation.ts";

export {
  CORE_SERVICE_IDS,
  RESEARCH_PHASES,
  RESEARCH_STEPS,
  approveBudgetRequest,
  collectUnverifiedClaims,
  createBudgetEnvelope,
  createAssertion,
  createAuditEntry,
  createClaim,
  createMemoryItem,
  createEvidenceBinding,
  createExperimentSpec,
  createExperimentRun,
  DOCKER_SANDBOX_PROFILES,
  EXPERIMENT_RUN_STATUSES,
  PAPER_DRAFT_STATUSES,
  PAPER_VENUE_TEMPLATES,
  DEFAULT_REVIEW_THRESHOLDS,
  REVIEW_DIMENSIONS,
  REVIEWER_PERSONAS,
  REVIEW_VERDICTS,
  createProjectCharter,
  createPaperDraft,
  createPeerReview,
  createReviewRubric,
  createResearchProject,
  createResearchPlanDraft,
  freezeResearchPlan,
  getNextResearchStep,
  isResearchPhase,
  isAssertionVerified,
  isClaimVerified,
  isIsoTimestamp,
  isDockerSandboxProfile,
  isExperimentRunStatus,
  isOneOf,
  isResearchStep,
  isPaperDraftStatus,
  isPaperVenueTemplateId,
  isReviewDimensionId,
  isReviewerPersona,
  isReviewVerdict,
  nowIsoTimestamp,
  rejectBudgetRequest,
  validateAssertion,
  validateAuditEntry,
  validateClaim,
  validateBudgetApprovalRequest,
  validateEvidenceBinding,
  validateExperimentSpec,
  validateExperimentRun,
  validateIdeaProposal,
  validateMemoryItem,
  validatePaperDraft,
  validatePaperCompileResult,
  validateProjectCharter,
  validateResearchProject,
  validateResearchPlan,
  validateResearchPlanDraft,
  validatePeerReview,
  validateReviewDecision,
  validateReviewRound,
  validateReviewRubric,
};

export type {
  ApprovalStatus,
  Assertion,
  AssertionType,
  AuditActor,
  AuditDetails,
  AuditEntry,
  BaselineComparison,
  BaselineSpec,
  BudgetApprovalRequest,
  BudgetEnvelope,
  Claim,
  ClaimAggregation,
  ClaimAuditStatus,
  ClaimStrength,
  CoreServiceId,
  CreateAssertionInput,
  CreateClaimInput,
  CreateEvidenceBindingInput,
  CreateExperimentSpecInput,
  CreateExperimentRunInput,
  CreateMemoryItemInput,
  CreatePaperDraftInput,
  CreatePeerReviewInput,
  CreateReviewRubricInput,
  CreateProjectCharterInput,
  CreateResearchPlanDraftInput,
  DockerSandboxProfile,
  EvidenceBinding,
  ExperimentArtifact,
  ExperimentExecutionRef,
  ExperimentExecutionRequest,
  ExperimentFailure,
  ExperimentFailureType,
  ExperimentSpec,
  ExperimentRun,
  ExperimentRunStatus,
  FreezeResearchPlanInput,
  IdeaProposal,
  ProjectGateState,
  IsoTimestamp,
  MemoryItem,
  MemoryLayer,
  PaperCompileResult,
  PaperDraft,
  PaperDraftStatus,
  PaperFigure,
  PaperSections,
  PaperVenueTemplateId,
  ProjectLifecycleStatus,
  ProjectCharter,
  PeerReview,
  ResearchPhase,
  ResearchPlanApproval,
  ResearchPlan,
  ResearchPlanDraft,
  ResearchProject,
  ResearchStep,
  ReviewDecision,
  ReviewDimensionAssessment,
  ReviewDimensionId,
  ReviewerPersona,
  ReviewRound,
  ReviewRubric,
  ReviewThresholds,
  ReviewVerdict,
  ServiceDescriptor,
  ValidationIssue,
};

export const contractSummary = {
  phases: RESEARCH_PHASES,
  steps: RESEARCH_STEPS,
  services: CORE_SERVICE_IDS,
};

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  console.log(JSON.stringify(contractSummary, null, 2));
}
